name: Run Robot Framework Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  robot-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework
          pip install robotframework-seleniumlibrary
          pip install robotframework-jsonlibrary
          pip install robotframework-excellibrary
          pip install robotframework-requests
          pip install robotframework-pabot

      - name: Run all Robot tests (root and Tests/)
        run: |
          pabot --outputdir results --processes 2 . Tests/
