name: Run Robot Framework Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  robot-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install robotframework-datadriver

      - name: Run Robot Framework Tests
        env:
          username: Admin
          os: ubuntu
        run: |
          robot \
            --variable URL:https://opensource-demo.orangehrmlive.com/web/index.php/auth/login \
            --variable BROWSER_OPTIONS:"--headless --disable-dev-shm-usage --no-sandbox --disable-gpu --remote-debugging-port=9222 --user-data-dir=/tmp/chrome-$(date +%s)" \
            Tests
