name: Run Robot Framework Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  robot-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install robotframework-datadriver[XLS]

      - name: Run Robot Framework Tests
        env:
          username: Admin
          os: ubuntu-latest
        run: |
          robot \
            --variable BROWSER:chrome \
            --variable OPTIONS:"add_argument(--headless); add_argument(--no-sandbox); add_argument(--disable-dev-shm-usage); add_argument(--disable-gpu); add_argument(--remote-debugging-port=9222); add_argument(--user-data-dir=/tmp/chrome-profile)" \
            --outputdir results \
            Tests/
